x-templates:
  - &app-base
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: .
    environment:
      CAMO_ORIGIN: https://localhost:4181
      API_ORIGIN: http://localhost:8080
      SOCKET_ORIGIN: ws://localhost:8080
      CAMO_KEY: "0x24FEEDFACEDEADBEEFCAFE"
      PORT: "3000"
    env_file:
      - atcouncil.env
      - .env
    volumes:
      - .:/workdir
      - ./container-node_modules/root:/workdir/node_modules
      - ./container-node_modules/bff:/workdir/packages/bff/node_modules
      - ./container-node_modules/client:/workdir/packages/client/node_modules
      - ./container-node_modules/common:/workdir/packages/common/node_modules

version: "3.4"
services:
  app:
    <<: *app-base
    command: ./bin/start-watch-bff.sh
    ports:
      - 3000:3000
  app-dev-server:
    <<: *app-base
    command: ./bin/build-and-start-watch.sh
    ports:
      - 3001:3001
  app-build:
    <<: *app-base
    command: ./bin/build-watch.sh
  app-codegen:
    <<: *app-base
    command: ./bin/codegen-watch.sh
  app-build-bff:
    <<: *app-base
    command: ./bin/build-watch-bff.sh
  camo:
    restart: always
    image: docker.pkg.github.com/anontown/camo-image/at-camo:e71d34c
    environment:
      CAMO_KEY: "0x24FEEDFACEDEADBEEFCAFE"
      PORT: "4181"
    ports:
      - 4181:4181
  atcouncil:
    restart: always
    image: docker.pkg.github.com/anontown/atcouncil/atcouncil:1a990b7
    environment:
      SERVER_PORT: "8080"
      MONGO_HOST: mongo:27017
      ES_HOST: es:9200
      REDIS_HOST: redis:6379
    env_file:
      - atcouncil.env
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - es
      - redis
  mongo:
    restart: always
    image: docker.pkg.github.com/anontown/mongo-image/at-mongo:db0fadb
    volumes:
      - ./data/db:/data/db
  es:
    restart: always
    image: docker.pkg.github.com/anontown/elasticsearch-image/at-elasticsearch:579c73d
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
  redis:
    restart: always
    image: docker.pkg.github.com/anontown/redis-image/at-redis:5b1114d
    volumes:
      - ./data/redis:/data
