name: ci

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: docker build -t app .
      - name: lint
        run: docker run --rm app npm run lint
  build-and-push:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v1
      - uses: anontown/docker-image-action@master
        with:
          image-name: atpark
          personal-token: ${{ secrets.PERSONAL_TOKEN }}
